


import type { Adventure, Scene, NPC, Location, Faction, Item } from './index';

/**
 * Represents an Adventure object before it's added to the campaign.
 * It does not have an `id`, and its `scenes` also lack `id`s.
 */
export type AdventureForBatchAdd = Omit<Adventure, 'id' | 'scenes'> & {
    scenes: Omit<Scene, 'id'>[];
};

/**
 * Defines the structure for a batch of new entities generated by the Evocation Wizard.
 */
export interface BatchAddData {
    npcs: (Omit<NPC, 'id' | 'knowsPlayerHistory'>)[];
    locations: (Omit<Location, 'id' | 'subLocationIds'>)[];
    factions: Omit<Faction, 'id' | 'leaderId' | 'memberIds'>[];
    adventures: AdventureForBatchAdd[];
    items: Omit<Item, 'id'>[];
}