
import {
  BookOpen,
  Users,
  Map,
  Shield,
  Plus,
  Trash2,
  ChevronDown,
  ChevronUp,
  Save,
  BrainCircuit,
  Dice5,
  Sparkles,
  Swords,
  ScrollText,
  MessageSquare,
  Compass,
  Puzzle,
  Bus,
  FileText,
  Sun,
  Moon,
  Wind,
  Droplets,
  HelpCircle,
  Settings,
  BookHeart,
  FileCode,
  Wand2,
  X,
  Link2,
  FileUp,
  FileDown,
  BookCopy,
  UsersRound,
  StickyNote,
  MessageCircle,
  Minimize2,
  Maximize2,
  CheckCircle2,
  Pencil,
  FolderOpen,
  Calendar,
  Play,
  Target,
  ListTodo,
  Minus,
  Square,
  SkipForward,
  Mic,
  MicOff,
  Clock,
  ChevronRight,
  Radio,
  Menu,
  Hash,
  Star,
  Filter,
  UserPlus,
  ArrowUpCircle,
  PauseCircle,
  CircleDot,
  Loader2,
  AlertTriangle,
  Clipboard,
} from 'lucide-react';

export const Icons = {
  Campaign: BookHeart,
  Setting: Settings,
  NPCs: Users,
  Locations: Map,
  Factions: Shield,
  Items: ScrollText,
  Adventures: BookOpen,
  Scenes: FileText,
  SessionLog: BookCopy,
  PlayerCharacters: UsersRound,
  Notes: StickyNote,
  Plus,
  Trash: Trash2,
  ChevronDown,
  ChevronUp,
  Save,
  Coach: BrainCircuit,
  Dice: Dice5,
  Sparkles,
  Combat: Swords,
  Social: MessageSquare,
  Exploration: Compass,
  Puzzle,
  Travel: Bus,
  Help: HelpCircle,
  FileCode,
  FileText,
  Wizard: Wand2,
  X,
  Link: Link2,
  FileUp,
  FileDown,
  Chat: MessageCircle,
  Minimize: Minimize2,
  Maximize: Maximize2,
  CheckCircle: CheckCircle2,
  Edit: Pencil,
  FolderOpen: FolderOpen,
  Calendar,
  Play,
  BookCopy,
  Plot: Target,
  Target: Target,
  List: ListTodo,
  Minus,
  Stop: Square,
  SkipForward,
  Mic,
  MicOff,
  Clock,
  ChevronRight,
  Live: Radio,
  Menu,
  Hash,
  Star,
  Filter,
  UserPlus,
  Advanced: ArrowUpCircle,
  Stalled: PauseCircle,
  Unchanged: CircleDot,
  Loader: Loader2,
  AlertTriangle,
  Clipboard,
};

export const SceneIcon = ({ type, className }: { type: string, className?: string }) => {
  const defaultClass = "w-4 h-4 mr-2";
  const combinedClass = `${defaultClass} ${className || ''}`;
  switch (type) {
    case 'combat':
      return <Icons.Combat className={combinedClass} />;
    case 'social':
      return <Icons.Social className={combinedClass} />;
    case 'exploration':
      return <Icons.Exploration className={combinedClass} />;
    case 'puzzle':
      return <Icons.Puzzle className={combinedClass} />;
    default:
      return <Icons.Scenes className={combinedClass} />;
  }
};
