
import type { Campaign, RollableTable } from '../../types/index';
import type { DormantPiece } from '../../utils/dormantMaterial';
import { generateText, generateWithSchema } from './core';
import { buildCampaignContext } from '../contextBuilder';

// --- Schemas ---

const rollableTableSchema = {
  type: 'object',
  properties: {
    title: { type: 'string', description: "A descriptive title for the table." },
    dieType: { type: 'string', description: "The type of die to roll, e.g., 'd6', 'd10', 'd20'." },
    entries: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          range: { type: 'string', description: "The roll or range for this result, e.g., '1', '2-3'." },
          result: { type: 'string', description: "The outcome for this roll." },
        },
        required: ['range', 'result'],
      },
    },
  },
  required: ['title', 'dieType', 'entries'],
};

export const sessionAnalysisSchema = {
  type: 'object',
  properties: {
    entries: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          content: { type: 'string', description: "A concise, single-sentence summary of a specific event or beat found in the notes." },
          relatedEntityNames: {
              type: 'array',
              items: { type: 'string' },
              description: "Names of known entities (NPCs, Locations, Factions) mentioned or involved in this event."
          }
        },
        required: ['content', 'relatedEntityNames']
      }
    }
  },
  required: ['entries']
};

export const sessionRecapSchema = {
  type: 'object',
  properties: {
    recap: { type: 'string', description: "A narrative recap of the session suitable for reading at the start of the next session (3-5 paragraphs). Written in past tense, third person. Engaging and dramatic." },
    looseEnds: {
      type: 'array',
      items: { type: 'string' },
      description: "A list of unresolved plot threads, unanswered questions, or dangling hooks from this session that the DM should follow up on."
    },
    playerFacingRecap: { type: 'string', description: "A shorter, player-safe version of the recap with any GM secrets or hidden information stripped out. Suitable for sharing with players between sessions." },
  },
  required: ['recap', 'looseEnds', 'playerFacingRecap'],
};

// E3: `generateSessionRecap` no longer calls the model against the combined
// shape above — it is kept exported (unused internally) purely so nothing
// that already imports it for its shape (tests/migration-verification.test.ts,
// docs) breaks. The real calls use the two schemas below, split so the
// player-facing half is generated by a SEPARATE model call that never sees
// the GM's `recap`/`looseEnds` prompt or campaign context. See
// tests/services/dmCoach.playerSafeRecap.test.ts.

const gmSessionRecapSchema = {
  type: 'object',
  properties: {
    recap: { type: 'string', description: "A narrative recap of the session suitable for reading at the start of the next session (3-5 paragraphs). Written in past tense, third person. Engaging and dramatic." },
    looseEnds: {
      type: 'array',
      items: { type: 'string' },
      description: "A list of unresolved plot threads, unanswered questions, or dangling hooks from this session that the DM should follow up on."
    },
  },
  required: ['recap', 'looseEnds'],
};

const playerSessionRecapSchema = {
  type: 'object',
  properties: {
    playerFacingRecap: { type: 'string', description: "A shorter, player-safe recap of the session for sharing directly with players. Must contain no GM secrets, hidden motivations, or information the players have not discovered." },
  },
  required: ['playerFacingRecap'],
};

export interface SessionRecapResult {
  recap: string;
  looseEnds: string[];
  playerFacingRecap: string;
}

/**
 * Campaign handle used to derive the **player-safe** context for the
 * player-facing half of a session recap (E3). The caller passes the campaign,
 * never a pre-built context string — `generateSessionRecap` builds the
 * `'player-safe'` variant itself so unrevealed GM truth cannot be handed in by
 * accident. See tests/services/dmCoach.playerSafeRecap.test.ts.
 */
export interface PlayerSafeRecapContext {
  campaign: Campaign;
  activeSceneId?: string;
  activeSessionId?: string;
  maxTokenEstimate?: number;
}

// --- Freeform Text Config ---

interface FreeformTextConfig {
  id: string;
  persona: string;
  taskDescription: string;
  outputConstraints: string;
  userPromptTemplate: string;  // Use {{prompt}} as placeholder
  defaultTier: string;
}

const narrationConfig: FreeformTextConfig = {
  id: 'narration',
  persona: 'a master Dungeon Master, in the style of Brennan Lee Mulligan or Matt Mercer',
  taskDescription: 'Your task is to generate evocative, sensory-rich narrative descriptions for a tabletop RPG. Do not break character.',
  outputConstraints: 'Based on the context and the following request, provide a short, compelling narrative description (2-4 sentences) that the DM can read aloud to the players.',
  userPromptTemplate: 'Request: "{{prompt}}"',
  defaultTier: 'standard',
};

const improvisationConfig: FreeformTextConfig = {
  id: 'improvisation',
  persona: 'a master Dungeon Master, an expert at improvisation',
  taskDescription: 'Your task is to help a fellow DM handle an unexpected player action in a tabletop RPG. Provide 2-3 immediate, actionable consequences and a potential long-term consequence. Present your response in a clear, easy-to-scan format (e.g., using bullet points or bold headings). Do not break character.',
  outputConstraints: '',
  userPromptTemplate: 'The players did something unexpected. Here is the situation:\n"{{prompt}}"\n\nWhat happens next?',
  defaultTier: 'standard',
};

const enhancedTextConfig: FreeformTextConfig = {
  id: 'enhanced-text',
  persona: 'a creative assistant for a Dungeon Master',
  taskDescription: 'Based on the provided context, generate a short, creative piece of text (2-4 sentences) for the requested field. Be concise and evocative.',
  outputConstraints: '',
  userPromptTemplate: 'Request: "{{prompt}}"',
  defaultTier: 'lite',
};

// --- Freeform Text Helper ---

function buildFreeformPrompt(config: FreeformTextConfig, prompt: string): string {
  return [
    `You are ${config.persona}.`,
    config.taskDescription,
    config.outputConstraints,
    '',
    config.userPromptTemplate.replace('{{prompt}}', () => prompt),
  ].filter(Boolean).join('\n\n');
}

// --- Generator Functions ---

export const generateNarration = (prompt: string, campaignContext?: string, useLiteModel: boolean = false): Promise<string> => {
  const tier = useLiteModel ? 'lite' : narrationConfig.defaultTier;
  const fullPrompt = buildFreeformPrompt(narrationConfig, prompt);
  return generateText(fullPrompt, tier, campaignContext);
};

export const generateImprovisation = (prompt: string, campaignContext?: string, useLiteModel: boolean = false): Promise<string> => {
  const tier = useLiteModel ? 'lite' : improvisationConfig.defaultTier;
  const fullPrompt = buildFreeformPrompt(improvisationConfig, prompt);
  return generateText(fullPrompt, tier, campaignContext);
};

export const generateRollableTable = (prompt: string, campaignContext?: string, useLiteModel: boolean = false): Promise<RollableTable> => {
  const modelName = useLiteModel ? 'lite' : 'standard';
  const instructions = `You are a creative Dungeon Master. Based on the campaign context and the user's prompt, generate a custom rollable table for a tabletop RPG. The table should be thematic and provide interesting, varied outcomes. The roll ranges should be contiguous and cover the full range of a standard die (like d4, d6, d8, d10, d12, or d20).`;
  return generateWithSchema(prompt, rollableTableSchema, instructions, {}, modelName, campaignContext);
};

export const generateEnhancedText = (prompt: string, campaignContext?: string): Promise<string> => {
  const tier = enhancedTextConfig.defaultTier;
  const fullPrompt = buildFreeformPrompt(enhancedTextConfig, prompt);
  return generateText(fullPrompt, tier, campaignContext);
};

export const generateSessionRecap = async (
    sessionNotes: string,
    plotSummaries: string,
    campaignContext?: string,
    // E3: when supplied, the player-facing half of the recap is generated in a
    // SEPARATE call whose context is derived here via
    // buildCampaignContext({ variant: 'player-safe', ... }), never handed a
    // pre-built string by the caller. See
    // tests/services/dmCoach.playerSafeRecap.test.ts.
    playerSafe?: PlayerSafeRecapContext
): Promise<SessionRecapResult> => {
    const modelName = 'standard';
    const prompt = `Here are the session notes to recap:\n\n${sessionNotes}`;

    // --- GM call: recap + loose ends, with full GM campaign context and plot plans ---
    const gmInstructions = `You are an expert Game Master's assistant. Your task is to generate a structured session recap from the DM's running notes.

You will produce two things:
1. **recap**: A narrative recap of the session (3-5 paragraphs). Written in past tense, third person. Engaging and dramatic, suitable for reading aloud at the start of the next session. Cover all major events, decisions, and encounters.
2. **looseEnds**: A list of unresolved plot threads, unanswered questions, cliffhangers, or dangling hooks that the DM should follow up on in future sessions. Be specific.

Active plot threads for context:
${plotSummaries}`;

    // --- Player call: playerFacingRecap ONLY, built from a player-safe context (or none) ---
    // The GM `campaignContext`/`plotSummaries` never reach this call — that is
    // the whole point of splitting it out (E3's hard revealed-only rule).
    const playerInstructions = `You are an expert Game Master's assistant, writing the PLAYER-FACING OUTPUT of a session recap for the party to read between sessions.

Produce **playerFacingRecap**: a shorter, engaging recap of what the party experienced and accomplished this session (past tense, third person), suitable for sharing directly with the players.

Never include unrevealed secrets, GM notes, hidden motivations, or any information the players have not discovered.`;

    const playerContext = playerSafe
      ? buildCampaignContext({
          variant: 'player-safe',
          campaign: playerSafe.campaign,
          activeSceneId: playerSafe.activeSceneId,
          activeSessionId: playerSafe.activeSessionId,
          maxTokenEstimate: playerSafe.maxTokenEstimate,
        })
      : undefined;

    const [gmResult, playerResult] = await Promise.all([
      generateWithSchema(prompt, gmSessionRecapSchema, gmInstructions, {}, modelName, campaignContext),
      generateWithSchema(prompt, playerSessionRecapSchema, playerInstructions, {}, modelName, playerContext),
    ]);

    return {
      recap: gmResult.recap,
      looseEnds: gmResult.looseEnds,
      playerFacingRecap: playerResult.playerFacingRecap,
    };
};

/**
 * P2 — the Callback Machine. The DM types nothing: the caller samples dormant
 * campaign material (`utils/dormantMaterial.ts`) and hands it here with the
 * coach-variant campaign context. Distinct from `generateImprovisation`, which
 * looks *forward* from a DM-typed situation; this looks *backward* into the
 * world's own idle inventory and reincorporates it.
 */
export interface CallbackComplicationRequest {
  /** The sampled dormant material to reincorporate. Must not be empty. */
  material: DormantPiece[];
  /** What is on stage right now, derived by the caller — never DM-typed. */
  sceneSummary?: string;
  /** Coach-variant campaign context, built by the caller. */
  campaignContext?: string;
  useLiteModel?: boolean;
}

/** One `- Label (reason)` bullet per sampled piece, in the order the caller supplied them. */
function formatDormantMaterialList(material: DormantPiece[]): string {
  return material.map((piece) => `- ${piece.label} (${piece.reason})`).join('\n');
}

/**
 * Builds the fully-synthesized prompt — there is no DM-typed text anywhere in
 * it (lazy-dm-lens.md §5's no-crafted-prompt rule made structural). Campaign
 * text (labels, reasons, the scene summary) is inserted via plain template
 * interpolation, never as the replacement argument of `.replace()`, so a `$&`
 * or `$$` in a title survives untouched.
 */
function buildCallbackComplicationPrompt(request: CallbackComplicationRequest): string {
  const sections = [
    'You are a master Dungeon Master, an expert at improvisation by reincorporation: the craft principle that the best twist is something the table has already established, not something invented from nothing.',
    `Dormant material from this campaign is available to spend right now:\n${formatDormantMaterialList(request.material)}`,
    request.sceneSummary ? `What is happening on stage right now: ${request.sceneSummary}` : '',
    'Write ONE complication for the current scene that reincorporates this material back into the story. Do not offer a menu of options — commit to a single complication the DM can read or paraphrase immediately (2-4 sentences). Do not break character.',
  ].filter(Boolean);

  return sections.join('\n\n');
}

export const generateCallbackComplication = async (
  request: CallbackComplicationRequest
): Promise<string> => {
  const material = request?.material ?? [];
  if (material.length === 0) {
    throw new Error(
      'generateCallbackComplication needs at least one piece of dormant material to reincorporate; the sample was empty.'
    );
  }
  const tier = request.useLiteModel ? 'lite' : 'standard';
  const prompt = buildCallbackComplicationPrompt(request);
  const result = await generateText(prompt, tier, request.campaignContext);
  return result.trim();
};

export const analyzeSessionNotes = async (notes: string, knownEntityNames: string[], campaignContext?: string): Promise<{entries: {content: string, relatedEntityNames: string[]}[]}> => {
    const modelName = 'standard';
    const instructions = `You are an expert Game Master's assistant. Your task is to process raw session notes into structured log entries.

    1. Break the notes down into distinct events.
    2. Summarize each event clearly and concisely.
    3. Identify if any of the following known entities are mentioned in the event:
    ${JSON.stringify(knownEntityNames)}

    Only list entities from the provided list in the 'relatedEntityNames' field.`;

    return generateWithSchema(notes, sessionAnalysisSchema, instructions, {}, modelName, campaignContext);
}
