
import type { Campaign, RollableTable } from '../../types/index';
import type { DormantPiece } from '../../utils/dormantMaterial';
import { generateText, generateWithSchema } from './core';
import { buildCampaignContext } from '../contextBuilder';
import { getPlayedSessionsInOrder, getLastCompletedSession } from '../../utils/storyDerivations';

// --- Schemas ---

const rollableTableSchema = {
  type: 'object',
  properties: {
    title: { type: 'string', description: "A descriptive title for the table." },
    dieType: { type: 'string', description: "The type of die to roll, e.g., 'd6', 'd10', 'd20'." },
    entries: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          range: { type: 'string', description: "The roll or range for this result, e.g., '1', '2-3'." },
          result: { type: 'string', description: "The outcome for this roll." },
        },
        required: ['range', 'result'],
      },
    },
  },
  required: ['title', 'dieType', 'entries'],
};

export const sessionAnalysisSchema = {
  type: 'object',
  properties: {
    entries: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          content: { type: 'string', description: "A concise, single-sentence summary of a specific event or beat found in the notes." },
          relatedEntityNames: {
              type: 'array',
              items: { type: 'string' },
              description: "Names of known entities (NPCs, Locations, Factions) mentioned or involved in this event."
          }
        },
        required: ['content', 'relatedEntityNames']
      }
    }
  },
  required: ['entries']
};

export const sessionRecapSchema = {
  type: 'object',
  properties: {
    recap: { type: 'string', description: "A narrative recap of the session suitable for reading at the start of the next session (3-5 paragraphs). Written in past tense, third person. Engaging and dramatic." },
    looseEnds: {
      type: 'array',
      items: { type: 'string' },
      description: "A list of unresolved plot threads, unanswered questions, or dangling hooks from this session that the DM should follow up on."
    },
    playerFacingRecap: { type: 'string', description: "A shorter, player-safe version of the recap with any GM secrets or hidden information stripped out. Suitable for sharing with players between sessions." },
  },
  required: ['recap', 'looseEnds', 'playerFacingRecap'],
};

// E3: `generateSessionRecap` no longer calls the model against the combined
// shape above — it is kept exported (unused internally) purely so nothing
// that already imports it for its shape (tests/migration-verification.test.ts,
// docs) breaks. The real calls use the two schemas below, split so the
// player-facing half is generated by a SEPARATE model call that never sees
// the GM's `recap`/`looseEnds` prompt or campaign context. See
// tests/services/dmCoach.playerSafeRecap.test.ts.

const gmSessionRecapSchema = {
  type: 'object',
  properties: {
    recap: { type: 'string', description: "A narrative recap of the session suitable for reading at the start of the next session (3-5 paragraphs). Written in past tense, third person. Engaging and dramatic." },
    looseEnds: {
      type: 'array',
      items: { type: 'string' },
      description: "A list of unresolved plot threads, unanswered questions, or dangling hooks from this session that the DM should follow up on."
    },
  },
  required: ['recap', 'looseEnds'],
};

const playerSessionRecapSchema = {
  type: 'object',
  properties: {
    playerFacingRecap: { type: 'string', description: "A shorter, player-safe recap of the session for sharing directly with players. Must contain no GM secrets, hidden motivations, or information the players have not discovered." },
  },
  required: ['playerFacingRecap'],
};

export interface SessionRecapResult {
  recap: string;
  looseEnds: string[];
  playerFacingRecap: string;
}

/**
 * Campaign handle used to derive the **player-safe** context for the
 * player-facing half of a session recap (E3). The caller passes the campaign,
 * never a pre-built context string — `generateSessionRecap` builds the
 * `'player-safe'` variant itself so unrevealed GM truth cannot be handed in by
 * accident. See tests/services/dmCoach.playerSafeRecap.test.ts.
 */
export interface PlayerSafeRecapContext {
  campaign: Campaign;
  activeSceneId?: string;
  activeSessionId?: string;
  maxTokenEstimate?: number;
}

// --- Freeform Text Config ---

interface FreeformTextConfig {
  id: string;
  persona: string;
  taskDescription: string;
  outputConstraints: string;
  userPromptTemplate: string;  // Use {{prompt}} as placeholder
  defaultTier: string;
}

const narrationConfig: FreeformTextConfig = {
  id: 'narration',
  persona: 'a master Dungeon Master, in the style of Brennan Lee Mulligan or Matt Mercer',
  taskDescription: 'Your task is to generate evocative, sensory-rich narrative descriptions for a tabletop RPG. Do not break character.',
  outputConstraints: 'Based on the context and the following request, provide a short, compelling narrative description (2-4 sentences) that the DM can read aloud to the players.',
  userPromptTemplate: 'Request: "{{prompt}}"',
  defaultTier: 'standard',
};

const improvisationConfig: FreeformTextConfig = {
  id: 'improvisation',
  persona: 'a master Dungeon Master, an expert at improvisation',
  taskDescription: 'Your task is to help a fellow DM handle an unexpected player action in a tabletop RPG. Provide 2-3 immediate, actionable consequences and a potential long-term consequence. Present your response in a clear, easy-to-scan format (e.g., using bullet points or bold headings). Do not break character.',
  outputConstraints: '',
  userPromptTemplate: 'The players did something unexpected. Here is the situation:\n"{{prompt}}"\n\nWhat happens next?',
  defaultTier: 'standard',
};

const enhancedTextConfig: FreeformTextConfig = {
  id: 'enhanced-text',
  persona: 'a creative assistant for a Dungeon Master',
  taskDescription: 'Based on the provided context, generate a short, creative piece of text (2-4 sentences) for the requested field. Be concise and evocative.',
  outputConstraints: '',
  userPromptTemplate: 'Request: "{{prompt}}"',
  defaultTier: 'lite',
};

// --- Freeform Text Helper ---

function buildFreeformPrompt(config: FreeformTextConfig, prompt: string): string {
  return [
    `You are ${config.persona}.`,
    config.taskDescription,
    config.outputConstraints,
    '',
    config.userPromptTemplate.replace('{{prompt}}', () => prompt),
  ].filter(Boolean).join('\n\n');
}

// --- Generator Functions ---

export const generateNarration = (prompt: string, campaignContext?: string, useLiteModel: boolean = false): Promise<string> => {
  const tier = useLiteModel ? 'lite' : narrationConfig.defaultTier;
  const fullPrompt = buildFreeformPrompt(narrationConfig, prompt);
  return generateText(fullPrompt, tier, campaignContext);
};

export const generateImprovisation = (prompt: string, campaignContext?: string, useLiteModel: boolean = false): Promise<string> => {
  const tier = useLiteModel ? 'lite' : improvisationConfig.defaultTier;
  const fullPrompt = buildFreeformPrompt(improvisationConfig, prompt);
  return generateText(fullPrompt, tier, campaignContext);
};

export const generateRollableTable = (prompt: string, campaignContext?: string, useLiteModel: boolean = false): Promise<RollableTable> => {
  const modelName = useLiteModel ? 'lite' : 'standard';
  const instructions = `You are a creative Dungeon Master. Based on the campaign context and the user's prompt, generate a custom rollable table for a tabletop RPG. The table should be thematic and provide interesting, varied outcomes. The roll ranges should be contiguous and cover the full range of a standard die (like d4, d6, d8, d10, d12, or d20).`;
  return generateWithSchema(prompt, rollableTableSchema, instructions, {}, modelName, campaignContext);
};

export const generateEnhancedText = (prompt: string, campaignContext?: string): Promise<string> => {
  const tier = enhancedTextConfig.defaultTier;
  const fullPrompt = buildFreeformPrompt(enhancedTextConfig, prompt);
  return generateText(fullPrompt, tier, campaignContext);
};

export const generateSessionRecap = async (
    sessionNotes: string,
    plotSummaries: string,
    campaignContext?: string,
    // E3: when supplied, the player-facing half of the recap is generated in a
    // SEPARATE call whose context is derived here via
    // buildCampaignContext({ variant: 'player-safe', ... }), never handed a
    // pre-built string by the caller. See
    // tests/services/dmCoach.playerSafeRecap.test.ts.
    playerSafe?: PlayerSafeRecapContext
): Promise<SessionRecapResult> => {
    const modelName = 'standard';
    const prompt = `Here are the session notes to recap:\n\n${sessionNotes}`;

    // --- GM call: recap + loose ends, with full GM campaign context and plot plans ---
    const gmInstructions = `You are an expert Game Master's assistant. Your task is to generate a structured session recap from the DM's running notes.

You will produce two things:
1. **recap**: A narrative recap of the session (3-5 paragraphs). Written in past tense, third person. Engaging and dramatic, suitable for reading aloud at the start of the next session. Cover all major events, decisions, and encounters.
2. **looseEnds**: A list of unresolved plot threads, unanswered questions, cliffhangers, or dangling hooks that the DM should follow up on in future sessions. Be specific.

Active plot threads for context:
${plotSummaries}`;

    // --- Player call: playerFacingRecap ONLY, built from a player-safe context (or none) ---
    // The GM `campaignContext`/`plotSummaries` never reach this call — that is
    // the whole point of splitting it out (E3's hard revealed-only rule).
    const playerInstructions = `You are an expert Game Master's assistant, writing the PLAYER-FACING OUTPUT of a session recap for the party to read between sessions.

Produce **playerFacingRecap**: a shorter, engaging recap of what the party experienced and accomplished this session (past tense, third person), suitable for sharing directly with the players.

Never include unrevealed secrets, GM notes, hidden motivations, or any information the players have not discovered.`;

    const playerContext = playerSafe
      ? buildCampaignContext({
          variant: 'player-safe',
          campaign: playerSafe.campaign,
          activeSceneId: playerSafe.activeSceneId,
          activeSessionId: playerSafe.activeSessionId,
          maxTokenEstimate: playerSafe.maxTokenEstimate,
        })
      : undefined;

    const [gmResult, playerResult] = await Promise.all([
      generateWithSchema(prompt, gmSessionRecapSchema, gmInstructions, {}, modelName, campaignContext),
      generateWithSchema(prompt, playerSessionRecapSchema, playerInstructions, {}, modelName, playerContext),
    ]);

    return {
      recap: gmResult.recap,
      looseEnds: gmResult.looseEnds,
      playerFacingRecap: playerResult.playerFacingRecap,
    };
};

/**
 * P2 — the Callback Machine. The DM types nothing: the caller samples dormant
 * campaign material (`utils/dormantMaterial.ts`) and hands it here with the
 * coach-variant campaign context. Distinct from `generateImprovisation`, which
 * looks *forward* from a DM-typed situation; this looks *backward* into the
 * world's own idle inventory and reincorporates it.
 */
export interface CallbackComplicationRequest {
  /** The sampled dormant material to reincorporate. Must not be empty. */
  material: DormantPiece[];
  /** What is on stage right now, derived by the caller — never DM-typed. */
  sceneSummary?: string;
  /** Coach-variant campaign context, built by the caller. */
  campaignContext?: string;
  useLiteModel?: boolean;
}

/** One `- Label (reason)` bullet per sampled piece, in the order the caller supplied them. */
function formatDormantMaterialList(material: DormantPiece[]): string {
  return material.map((piece) => `- ${piece.label} (${piece.reason})`).join('\n');
}

/**
 * Builds the fully-synthesized prompt — there is no DM-typed text anywhere in
 * it (lazy-dm-lens.md §5's no-crafted-prompt rule made structural). Campaign
 * text (labels, reasons, the scene summary) is inserted via plain template
 * interpolation, never as the replacement argument of `.replace()`, so a `$&`
 * or `$$` in a title survives untouched.
 */
function buildCallbackComplicationPrompt(request: CallbackComplicationRequest): string {
  const sections = [
    'You are a master Dungeon Master, an expert at improvisation by reincorporation: the craft principle that the best twist is something the table has already established, not something invented from nothing.',
    `Dormant material from this campaign is available to spend right now:\n${formatDormantMaterialList(request.material)}`,
    request.sceneSummary ? `What is happening on stage right now: ${request.sceneSummary}` : '',
    'Write ONE complication for the current scene that reincorporates this material back into the story. Do not offer a menu of options — commit to a single complication the DM can read or paraphrase immediately (2-4 sentences). Do not break character.',
  ].filter(Boolean);

  return sections.join('\n\n');
}

export const generateCallbackComplication = async (
  request: CallbackComplicationRequest
): Promise<string> => {
  const material = request?.material ?? [];
  if (material.length === 0) {
    throw new Error(
      'generateCallbackComplication needs at least one piece of dormant material to reincorporate; the sample was empty.'
    );
  }
  const tier = request.useLiteModel ? 'lite' : 'standard';
  const prompt = buildCallbackComplicationPrompt(request);
  const result = await generateText(prompt, tier, request.campaignContext);
  return result.trim();
};

/**
 * §4.2 — GM Intrusion (Monte Cook / Cypher System). Structurally a sibling of
 * `generateCallbackComplication` above, but with the one precondition that
 * function has and this one deliberately does not: it never requires dormant
 * material and never throws on an empty campaign. Session 1 of a brand-new
 * campaign has nothing dormant yet — this is the button that still works that
 * night. Where the Callback Machine looks *backward* into the world's own
 * idle inventory, this looks *forward*: it introduces something NEW, right
 * now, unprompted by any failed roll or specific trigger — the Cypher
 * System's own GM Intrusion technique. The mechanic's reward-economy half
 * (the XP exchange) is deliberately out of scope: Realmweaver carries the
 * posture, never a rules engine, the same call the Callback Machine already
 * made.
 */
function buildGmIntrusionPrompt(sceneSummary?: string): string {
  const sections = [
    'You are a master Dungeon Master practicing the GM Intrusion technique from the Cypher System: at any moment, unprompted by a failed roll or any specific trigger, you introduce ONE unexpected complication or twist that raises the stakes or pushes the scene forward.',
    sceneSummary ? `What is happening on stage right now: ${sceneSummary}` : '',
    'Commit to a single complication (2-4 sentences), not a menu of options. Look forward — introduce something new rather than reincorporating what has already happened. Do not break character.',
  ];
  return sections.filter(Boolean).join('\n\n');
}

export const generateGmIntrusion = async (
  campaignContext?: string,
  sceneSummary?: string,
  useLiteModel: boolean = false
): Promise<string> => {
  const tier = useLiteModel ? 'lite' : 'standard';
  const prompt = buildGmIntrusionPrompt(sceneSummary);
  const result = await generateText(prompt, tier, campaignContext);
  return result.trim();
};

// --- §4.8 — Extras & spear-carriers (Sly Flourish step 6) -------------------
//
// Scoped to the truly disposable case the shipped Quick NPC Generator doesn't
// target: not a full NPC record, just a name and one vivid one-line detail,
// four to six at a time, for a crowd scene that needs bodies in it right now.

const extrasSchema = {
  type: 'object',
  properties: {
    extras: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'A name for a throwaway background character.' },
          detail: {
            type: 'string',
            description: 'ONE vivid one-line detail — an accent, a scar, a nervous habit. No backstory or motivation.',
          },
        },
        required: ['name', 'detail'],
      },
    },
  },
  required: ['extras'],
};

export interface ExtraNpc {
  name: string;
  detail: string;
}

/**
 * Drops any draft missing a name or a detail and caps the list — the same
 * defensive shape-normalization every schema-backed generator applies to
 * model output before it reaches a component.
 */
function normalizeExtras(raw: unknown): ExtraNpc[] {
  if (!Array.isArray(raw)) return [];
  const result: ExtraNpc[] = [];
  for (const item of raw) {
    if (!item || typeof item !== 'object') continue;
    const record = item as Record<string, unknown>;
    const name = typeof record.name === 'string' ? record.name.trim() : '';
    const detail = typeof record.detail === 'string' ? record.detail.trim() : '';
    if (!name || !detail) continue;
    result.push({ name, detail });
    if (result.length >= 8) break;
  }
  return result;
}

export const generateExtras = async (
  count: number,
  campaignContext?: string,
  useLiteModel: boolean = false
): Promise<ExtraNpc[]> => {
  const tier = useLiteModel ? 'lite' : 'standard';
  const requested = Number.isFinite(count) ? Math.min(8, Math.max(1, Math.floor(count))) : 5;
  const instructions = `You are a Dungeon Master's assistant. Generate ${requested} throwaway background characters for a crowd scene — just a name and ONE vivid one-line detail each (an accent, a scar, a nervous habit). These are not major characters; do not give them backstories or motivations.`;
  const result = await generateWithSchema(`Generate ${requested} extras.`, extrasSchema, instructions, {}, tier, campaignContext);
  return normalizeExtras(result?.extras);
};

/**
 * P4 — the "Previously on…" cold open. The DM types nothing: the whole draft is
 * composed from what the campaign already holds — the last completed session's
 * `recap` and `looseEnds`, plus the most recent engraved moments (starred
 * `SessionLogEntry.isImportant` entries, zero new schema) — and written in the
 * campaign's `styleProfile` voice when one has been analysed.
 */
export interface ColdOpenRequest {
  /** The campaign the cold open is drafted from. Nothing else is read. */
  campaign: Campaign;
  /** Caller-built campaign context, forwarded verbatim. Never built here. */
  campaignContext?: string;
  useLiteModel?: boolean;
}

/** Cap on how many engraved moments are handed to the model — a spine, not a transcript. */
const MAX_COLD_OPEN_MOMENTS = 5;

/**
 * Every engraved moment (a starred `SessionLogEntry` with real words in it)
 * across every PLAYED session (`completed` or `active` — a star from the
 * live session counts, same as the Moments reel), oldest first: sessions in
 * `getPlayedSessionsInOrder`'s order, entries within a session in the order
 * they were logged (array order, never the timestamp — see
 * `utils/storyDerivations.ts` and `tests/momentsReel.view.test.tsx`).
 *
 * Deliberately re-walked here rather than shared with `TonightsTable.tsx`'s
 * reel — both derive from `getPlayedSessionsInOrder`, but a single hoisted
 * walker belongs in `utils/storyDerivations.ts`, outside this lane's file
 * allowlist. Flagged as a follow-up rather than done here.
 */
function gatherEngravedMoments(campaign: Campaign): string[] {
  const moments: string[] = [];
  for (const session of getPlayedSessionsInOrder(campaign)) {
    for (const note of session.structuredNotes ?? []) {
      if (note.isImportant && (note.content ?? '').trim()) {
        moments.push(note.content);
      }
    }
  }
  return moments;
}

/**
 * True when the campaign holds anything a cold open could be written from:
 * words in the last completed session's recap or loose ends, or at least one
 * engraved moment anywhere. Pure — re-exported through `aiService.ts` so the
 * Session Prep Wizard can decide whether to offer the action at all.
 */
export const hasColdOpenMaterial = (campaign: Campaign): boolean => {
  const lastCompleted = getLastCompletedSession(campaign);
  const hasRecap = !!(lastCompleted?.recap ?? '').trim();
  const hasLooseEnds = !!(lastCompleted?.looseEnds ?? '').trim();
  return hasRecap || hasLooseEnds || gatherEngravedMoments(campaign).length > 0;
};

export const generateColdOpen = async (request: ColdOpenRequest): Promise<string> => {
  const { campaign, campaignContext, useLiteModel } = request;

  if (!hasColdOpenMaterial(campaign)) {
    throw new Error(
      'There is nothing to draft a cold open from yet — write a recap, a loose end, or star a moment first.'
    );
  }

  const lastCompleted = getLastCompletedSession(campaign);
  const recapText = (lastCompleted?.recap ?? '').trim();
  const looseEndsText = (lastCompleted?.looseEnds ?? '').trim();
  const moments = gatherEngravedMoments(campaign).slice(-MAX_COLD_OPEN_MOMENTS).reverse();
  const styleText = (campaign.styleProfile ?? '').trim();

  const sections = [
    'You are a master Dungeon Master\'s assistant. Draft a "Previously on…" cold open: read-aloud performance material of roughly 150 words that the DM can read aloud verbatim to open tonight\'s session, the way a returning show recaps itself. Write continuous prose — no bullet points, no headings, no meta-commentary about the task.',
    recapText ? `Last session's recap:\n${recapText}` : '',
    looseEndsText ? `Loose ends still hanging from last session:\n${looseEndsText}` : '',
    moments.length > 0
      ? `The engraved moments from this campaign, newest first:\n${moments.map((m) => `- ${m}`).join('\n')}`
      : '',
    styleText ? `Match this campaign's voice guide exactly:\n${styleText}` : '',
  ].filter(Boolean);

  const prompt = sections.join('\n\n');
  const tier = useLiteModel ? 'lite' : 'standard';
  const result = await generateText(prompt, tier, campaignContext);
  return result.trim();
};

// --- Scene Menu Generator (docs/design/lazy-dm-lens.md §4 R1 / the "scene
// menu"; Wave 2, SessionPrepWizard bundle) -----------------------------------
//
// Widens the lazy path's Beats step, which ships with zero AI assist today,
// with the same generate -> preview -> keep-some idiom R2 already shipped for
// the Secrets Tracker (`generateSecretBatch` above / `GenerateTenPanel`), one
// step down in scale: 5-6 short scene drafts instead of ten secrets. The
// "prompt" handed to the model is a fixed constant — the DM never sees or
// edits a text box (docs/design/lazy-dm-lens.md §5's no-crafted-prompt rule).

/**
 * One proposed scene, before the DM keeps it. Maps directly onto the shipped
 * `Beat` shape (`title` -> `title`, `hook` -> `notes`) — nothing here is
 * persisted until the DM checks it and the wizard folds it into its own
 * `lazyBeats` state. Deliberately NOT a `types/` shape, same reasoning as R2's
 * `SecretDraft`.
 */
export interface SceneMenuDraft {
  title: string;
  hook?: string;
}

/** A runaway model must not flood the preview panel. */
const MAX_SCENE_MENU_DRAFTS = 8;

const sceneMenuDraftSchema = {
  type: 'object',
  properties: {
    title: { type: 'string', description: 'A short, one-line title for a possible scene tonight.' },
    hook: { type: 'string', description: "Optional: one sentence of texture or a hook for the scene. Omit if the title says enough on its own." },
  },
  required: ['title'],
};

const sceneMenuSchema = {
  type: 'object',
  properties: {
    scenes: {
      type: 'array',
      description: 'Five to six possible short scenes for tonight, offered as a MENU — not a fixed sequence, and not all of them will be used.',
      items: sceneMenuDraftSchema,
    },
  },
  required: ['scenes'],
};

const SCENE_MENU_INSTRUCTIONS = `You are a master Dungeon Master helping a fellow GM outline potential scenes for tonight's table. Propose 5-6 possible short scenes the party might run into tonight, as a MENU the DM can pick from — not a fixed sequence, and not all of them will be used. Ground them in the loose ends, active plot threads, and NPCs or locations already established in the campaign. Each is a one-line title and, optionally, one sentence of texture.

- **title:** A short, evocative one-line scene title.
- **hook:** Optional — one sentence of texture or a hook. Omit if the title says enough on its own.`;

/** Fixed constant — the DM never types or edits this. Zero-prompt by construction. */
const SCENE_MENU_PROMPT = 'Propose 5-6 possible short scenes the party might run into tonight, as a menu I can pick from — not a fixed sequence.';

/**
 * Model output is made structurally safe HERE, not downstream: accepts a
 * `{ scenes: [...] }` envelope or a bare array, drops any entry missing a
 * non-blank `title`, omits a blank `hook` rather than storing `''`, and caps
 * the result at `MAX_SCENE_MENU_DRAFTS`. Always returns an array — never
 * throws on malformed model output (a rejected provider call is a different
 * matter and is left to propagate).
 */
function normalizeSceneMenuDrafts(raw: unknown): SceneMenuDraft[] {
  let list: unknown[];
  if (Array.isArray(raw)) {
    list = raw;
  } else if (raw && typeof raw === 'object' && Array.isArray((raw as { scenes?: unknown }).scenes)) {
    list = (raw as { scenes: unknown[] }).scenes;
  } else {
    return [];
  }

  const drafts: SceneMenuDraft[] = [];
  for (const entry of list) {
    if (drafts.length >= MAX_SCENE_MENU_DRAFTS) break;
    if (!entry || typeof entry !== 'object') continue;

    const entryObj = entry as Record<string, unknown>;
    const title = typeof entryObj.title === 'string' ? entryObj.title.trim() : '';
    if (!title) continue;

    const draft: SceneMenuDraft = { title };
    const hook = typeof entryObj.hook === 'string' ? entryObj.hook.trim() : '';
    if (hook) draft.hook = hook;

    drafts.push(draft);
  }
  return drafts;
}

/**
 * §4.1 — one model call proposes 5-6 possible scenes for tonight from
 * campaign context alone. Never throws on malformed model output: the result
 * is always an array (possibly empty). A provider-level rejection (network,
 * timeout, bad JSON after retries) propagates rather than being swallowed
 * into `[]`.
 */
export const generateSceneMenu = async (campaignContext?: string): Promise<SceneMenuDraft[]> => {
  const raw = await generateWithSchema(SCENE_MENU_PROMPT, sceneMenuSchema, SCENE_MENU_INSTRUCTIONS, {}, 'standard', campaignContext);
  return normalizeSceneMenuDrafts(raw);
};

// --- Strong Start Styles (docs/design/lazy-dm-lens.md §4.6; widens R1/P4) ---
//
// The shipped cold open ("Previously on…") is one drafting angle for Shea's
// step 2, and it depends on there being a prior session to recap. These two
// styles cover the rest: one that needs no history at all ('action'), and one
// built around exactly one sampled piece of the campaign's own dormant
// material ('reincorporate'). The 'previously-on' style is NOT handled here —
// callers continue to call `generateColdOpen` verbatim; this function only
// ever drafts 'action' or 'reincorporate'.

export interface StrongStartRequest {
  /** Which style to draft. 'previously-on' stays on `generateColdOpen` — it is deliberately not a member of this union. */
  style: 'action' | 'reincorporate';
  /** The campaign the strong start is drafted for — read only for its optional `styleProfile` voice guide, same precedent as `generateColdOpen`. */
  campaign: Campaign;
  /** Caller-built campaign context, forwarded verbatim. Never built here. */
  campaignContext?: string;
  /** Required for style 'reincorporate' — the ONE sampled dormant piece (`utils/dormantMaterial.ts`, read-only here) to build the opening around. */
  dormantPiece?: DormantPiece;
  useLiteModel?: boolean;
}

function styleGuideSection(campaign: Campaign): string {
  const styleText = (campaign.styleProfile ?? '').trim();
  return styleText ? `Match this campaign's voice guide exactly:\n${styleText}` : '';
}

function buildActionStrongStartPrompt(campaign: Campaign): string {
  const sections = [
    'You are a master Dungeon Master\'s assistant. Draft an in-medias-res strong start: read-aloud performance material of roughly 50-80 words that the DM can read aloud verbatim to open tonight\'s session by dropping the party straight into a moment of tension or motion — no recap, no setup, just action already underway. Write continuous prose — no bullet points, no headings, no meta-commentary about the task.',
    styleGuideSection(campaign),
  ].filter(Boolean);
  return sections.join('\n\n');
}

function buildReincorporateStrongStartPrompt(campaign: Campaign, dormantPiece: DormantPiece): string {
  const sections = [
    `You are a master Dungeon Master's assistant. Draft a strong start built around this piece of the campaign's own history: ${dormantPiece.label} — ${dormantPiece.reason}. Write read-aloud performance material of roughly 50-80 words that the DM can read aloud verbatim, bringing it back into the light as the hook for tonight. Write continuous prose — no bullet points, no headings, no meta-commentary about the task.`,
    styleGuideSection(campaign),
  ].filter(Boolean);
  return sections.join('\n\n');
}

/**
 * §4.6 — the DM types nothing in either style. 'reincorporate' needs a
 * sampled dormant piece to build around; asking for it with none supplied is
 * a caller mistake this refuses rather than papering over (same posture as
 * `generateCallbackComplication`'s empty-material guard above).
 */
export const generateStrongStart = async (request: StrongStartRequest): Promise<string> => {
  const { style, campaign, campaignContext, dormantPiece, useLiteModel } = request;

  let prompt: string;
  if (style === 'reincorporate') {
    if (!dormantPiece) {
      throw new Error(
        'generateStrongStart needs a sampled dormant piece for the "reincorporate" style; none was supplied.'
      );
    }
    prompt = buildReincorporateStrongStartPrompt(campaign, dormantPiece);
  } else {
    prompt = buildActionStrongStartPrompt(campaign);
  }

  const tier = useLiteModel ? 'lite' : 'standard';
  const result = await generateText(prompt, tier, campaignContext);
  return result.trim();
};

export const analyzeSessionNotes = async (notes: string, knownEntityNames: string[], campaignContext?: string): Promise<{entries: {content: string, relatedEntityNames: string[]}[]}> => {
    const modelName = 'standard';
    const instructions = `You are an expert Game Master's assistant. Your task is to process raw session notes into structured log entries.

    1. Break the notes down into distinct events.
    2. Summarize each event clearly and concisely.
    3. Identify if any of the following known entities are mentioned in the event:
    ${JSON.stringify(knownEntityNames)}

    Only list entities from the provided list in the 'relatedEntityNames' field.`;

    return generateWithSchema(notes, sessionAnalysisSchema, instructions, {}, modelName, campaignContext);
}

// ---------------------------------------------------------------------------
// Table Pulse (lazy-dm-research.md §4.3) — "Ask the Table" check-in questions
// ---------------------------------------------------------------------------
//
// This is P5's narrowest slice (storyteller-first-design.md P5):
// `PlayerCharacter.playerFlags` only. `Campaign.pillars` and
// `PlayerCharacter.hooks[]` stay gated — not built here, not implied by this
// change.

/**
 * "Ask the Table": a zero-prompt DM Coach tool (docs/design/lazy-dm-lens.md
 * §5 — no crafted prompt as the entry point) that hands the DM a short list
 * of warm, between-session questions to copy and send to their players.
 * Unlike `generateCallbackComplication`, there is no material precondition —
 * this always has something to offer, even for a brand-new campaign with an
 * empty roster.
 */
export interface CheckInQuestionsRequest {
  /**
   * Read ONLY for `playerCharacters[].playerFlags` (the players' own stated
   * appetites) — nothing else on the campaign is touched here.
   * `contextBuilder.ts` is deliberately NOT the source for this section; a
   * separate, later change owns injecting `playerFlags` into the shared
   * tiered context.
   */
  campaign?: Campaign;
  /** Caller-built campaign context, forwarded verbatim. Never built here. */
  campaignContext?: string;
  useLiteModel?: boolean;
}

const checkInQuestionsSchema = {
  type: 'object',
  properties: {
    questions: {
      type: 'array',
      description: 'Four to five short, warm between-session questions a GM could text their players.',
      items: { type: 'string' },
    },
  },
  required: ['questions'],
};

/** Zero DM-typed input — the "prompt" is always this fixed constant. */
const CHECK_IN_QUESTIONS_PROMPT = 'Propose a few check-in questions the DM can send the players between sessions.';

/** Hard cap so a verbose model response can't turn a glanceable list into a chore to read. */
const MAX_CHECK_IN_QUESTIONS = 6;

/**
 * Every non-blank line across the whole roster's `playerFlags`, in roster
 * order. A PC with none, a roster with none, or a missing campaign
 * contributes nothing — this never throws on an empty campaign.
 */
function gatherPlayerFlags(campaign?: Campaign): string[] {
  const flags: string[] = [];
  for (const pc of campaign?.playerCharacters ?? []) {
    for (const flag of pc.playerFlags ?? []) {
      const trimmed = flag.trim();
      if (trimmed) flags.push(trimmed);
    }
  }
  return flags;
}

/**
 * Model output made structurally safe HERE, mirroring `realmWeaver.ts`'s
 * `normalizeSecretDrafts`: accepts a `{ questions: [...] }` envelope or a
 * bare array, drops anything that isn't a non-blank string, and caps the
 * result at `MAX_CHECK_IN_QUESTIONS`. Always returns an array — never throws
 * on malformed model output.
 */
function normalizeCheckInQuestions(raw: unknown): string[] {
  let list: unknown[];
  if (Array.isArray(raw)) {
    list = raw;
  } else if (raw && typeof raw === 'object' && Array.isArray((raw as { questions?: unknown }).questions)) {
    list = (raw as { questions: unknown[] }).questions;
  } else {
    return [];
  }

  const questions: string[] = [];
  for (const entry of list) {
    if (questions.length >= MAX_CHECK_IN_QUESTIONS) break;
    if (typeof entry !== 'string') continue;
    const trimmed = entry.trim();
    if (trimmed) questions.push(trimmed);
  }
  return questions;
}

export const generateCheckInQuestions = async (request: CheckInQuestionsRequest = {}): Promise<string[]> => {
  const { campaign, campaignContext, useLiteModel } = request;
  const flags = gatherPlayerFlags(campaign);

  const instructions = [
    "You are a Game Master's assistant helping a DM check in with their players between sessions.",
    'Propose 4-5 short, warm questions a GM could text their players — things like what their character wants right now, what they wish had happened, or who they want to see again. Keep each under 15 words. Return only the questions themselves, no numbering or preamble.',
    flags.length > 0
      ? `Players have said they want more of:\n${flags.map((flag) => `- ${flag}`).join('\n')}`
      : '',
  ].filter(Boolean).join('\n\n');

  const tier = useLiteModel ? 'lite' : 'standard';
  const raw = await generateWithSchema(CHECK_IN_QUESTIONS_PROMPT, checkInQuestionsSchema, instructions, {}, tier, campaignContext);
  return normalizeCheckInQuestions(raw);
};
